# Site settings
title: Adam Single
email: adam@adamsingle.com
description: > # this means to ignore newlines until "baseurl:"
  Adventures in game development
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://adamsingle.github.io" # the base hostname and protocol for your site
twitter_username: adamsingle
github_username: adamsingle
show_downloads: false
theme: jekyll-theme-midnight

# Build settings 
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM